server:
  port: 12021
  servlet:
    encoding:
      charset: utf-8
      force-response: true
spring:
  application:
    name: eurekaServer
eureka:
  instance:
    hostname: 127.0.0.1.nip.io
  client:
    service-url:
      defaultZone: http://127-0-0-1.nip.io:12022/eureka/